Database:
  DBType: mysql
  UserName: root
  Password: root
  Host: localhost:3306
  DBName: newbee
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Server:
  RunMode: debug
  HttpPort: 8088
  ReadTimeout: 60
  WriteTimeout: 60
Log:
  LogFilePath: ./runtime/logs
  LogInfoFileName: info
  LogWarnFileName: warn
  LogFileExt: log
AccessLog:
  LogFilePath: ./runtime/logs
  LogFileName: access
  LogFileExt: log
Static:
  StaticDir: /static
ArticleImage:
  UploadDir: /static/uploads
  ImageHost: http://127.0.0.1:8088

